workshop:
  publishedID: 3649585996
  visibility: Private
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: |
    'v1.0: Sliders for Supporter Upgrade DLC (*no effect without that DLC). Adjusted some slider ranges.'
    'v0.1: Initial release.'
  tags:
  - Customization
  - UI
  - Utilities
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs:
  files:
  - enabled: true
    relative: true
    path: source/obj/Debug/LiveryGUI.dll
extraFiles: 
